nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
nohup kubectl exec -it loadtest2 /stress.sh &
