apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loadtest1
  name: loadtest1
spec:
  containers:
  - args:
    - sleep
    - 9999999999d
    image: busybox
    name: loadtest
    resources:
      limits:
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: worker01

status: {}
