apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loadtest2_1core
  name: loadtest2_1core
spec:
  containers:
  - args:
    - sleep
    - 9999999999d
    image: busybox
    name: loadtest
    resources:
      limits:
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: worker02

status: {}
